name: flutter_cinemapedia
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.2.4
  intl: ^0.20.2
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  analyzer: ^8.2.0
  build_runner: ^2.8.0
  change_app_package_name: ^1.5.0
  drift_dev: ^2.28.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
